'use strict';

module.exports = {
  BETTING_CASHBACK_RATE: Number(process.env.BETTING_CASHBACK_RATE || 0.005),
  DAILY_LOGIN_POINTS: Number(process.env.DAILY_LOGIN_POINTS || 5),
  DEVICE_COOLING_CAP_NAIRA: Number(process.env.DEVICE_COOLING_CAP_NAIRA || 20000),
  DEVICE_COOLING_HOURS: Number(process.env.DEVICE_COOLING_HOURS || 24),
  EDUCATION_CASHBACK_RATE: Number(process.env.EDUCATION_CASHBACK_RATE || 0.02),
  EDUCATION_CONVENIENCE_FEE: Number(process.env.EDUCATION_CONVENIENCE_FEE || 100),
  EDUCATION_PRICES: {
    WAEC_RESULT: Number(process.env.PRICE_WAEC_RESULT || 4500),
    WAEC_GCE: Number(process.env.PRICE_WAEC_GCE || 18000),
    JAMB: Number(process.env.PRICE_JAMB || 6200),
    NECO: Number(process.env.PRICE_NECO || 1500),
    NABTEB: Number(process.env.PRICE_NABTEB || 1500),
  },
  GOLD_TO_NAIRA_RATIO: Number(process.env.GOLD_TO_NAIRA_RATIO || 0.1),
  GOVERNMENT_CASHBACK_RATE: Number(process.env.GOVERNMENT_CASHBACK_RATE || 0.005),
  LIVE_CODE_MAX_WINNERS: Number(process.env.LIVE_CODE_MAX_WINNERS || 500),
  LIVE_CODE_REWARD_POINTS: Number(process.env.LIVE_CODE_REWARD_POINTS || 50),
  REFERRAL_POINTS: Number(process.env.REFERRAL_POINTS || 25),
  SPORTS_CACHE_TTL_MS: Number(process.env.SPORTS_CACHE_TTL_MS || 60 * 1000),
  TRANSPORT_CASHBACK_RATE: Number(process.env.TRANSPORT_CASHBACK_RATE || 0.01),
  TV_INTERNET_CASHBACK_RATE: Number(process.env.TV_INTERNET_CASHBACK_RATE || 0.015),
  UTILITY_CASHBACK_RATE: Number(process.env.UTILITY_CASHBACK_RATE || 0.01),
};
