import 'package:bayright9ja_mobile/core/theme/br9_theme.dart';
import 'package:flutter/material.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class GovReceiptPage extends StatelessWidget {
  const GovReceiptPage({
    super.key,
    required this.rrr,
    required this.amount,
    required this.serviceType,
    required this.status,
    this.reference = '',
  });

  final String rrr;
  final double amount;
  final String serviceType;
  final String status;
  final String reference;

  Future<void> _printReceipt() async {
    final document = pw.Document();
    document.addPage(
      pw.Page(
        build: (context) => pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'BR9ja Government Payment Receipt',
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 24),
              pw.Text('RRR: $rrr', style: pw.TextStyle(fontSize: 18)),
              pw.Text('Service: $serviceType'),
              pw.Text('Amount: NGN ${amount.toStringAsFixed(2)}'),
              pw.Text('Status: $status'),
              if (reference.isNotEmpty) pw.Text('Reference: $reference'),
              pw.SizedBox(height: 24),
              pw.Text(
                'Generated by BR9ja Wallet. Present this receipt where proof is required.',
              ),
            ],
          ),
        ),
      ),
    );
    await Printing.layoutPdf(onLayout: (_) async => document.save());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.deepNavy,
      appBar: AppBar(
        title: const Text('Government Receipt'),
        backgroundColor: AppColors.deepNavy,
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          Container(
            padding: const EdgeInsets.all(22),
            decoration: BoxDecoration(
              color: const Color(0xFF0A223D),
              borderRadius: BorderRadius.circular(26),
              border: Border.all(color: Colors.white10),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('RRR', style: TextStyle(color: Colors.white70)),
                const SizedBox(height: 8),
                SelectableText(
                  rrr,
                  style: const TextStyle(
                    color: AppColors.neonGold,
                    fontSize: 34,
                    fontWeight: FontWeight.w900,
                    letterSpacing: 1.4,
                  ),
                ),
                const SizedBox(height: 20),
                _Row(label: 'Service', value: serviceType),
                _Row(label: 'Amount', value: '₦${amount.toStringAsFixed(2)}'),
                _Row(label: 'Status', value: status),
                if (reference.isNotEmpty)
                  _Row(label: 'Reference', value: reference),
              ],
            ),
          ),
          const SizedBox(height: 22),
          FilledButton.icon(
            onPressed: _printReceipt,
            icon: const Icon(Icons.picture_as_pdf_rounded),
            label: const Text('Download PDF Receipt'),
          ),
        ],
      ),
    );
  }
}

class _Row extends StatelessWidget {
  const _Row({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        children: [
          Text(label, style: const TextStyle(color: Colors.white70)),
          const Spacer(),
          Flexible(
            child: Text(
              value,
              textAlign: TextAlign.right,
              style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.w800,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
